name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Dumpify
     
    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ./src/Dumpify

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      working-directory: ./src/Dumpify