name: Deploy Nuget Package

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
   
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/Dumpify
     
    - name: Build
      run: dotnet build -c Release --no-restore
      working-directory: ./src/Dumpify

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      working-directory: ./src/Dumpify
      
    - name: Create Nuget Package
      run: dotnet pack -c Release /p:VersionNumber=${{github.event.release.tag_name}} /p:PackageReleaseNotes="See https://github.com/MoaidHathot/Dumpify/releases/tag/${{github.event.release.tag_name}}" ./src/Dumpify/Dumpify.csproj
    
    - name: Archive Nuget Package for Dumpify
      uses: actions/upload-artifact@v1
      with:
        name: packages
        path: "./src/Dumpify/bin/Release/Dumpify.${{github.event.release.tag_name}}.nupkg"

    - name: Publish Nuget Package
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json

      
